name: projeto-devops

on:
  push:
    branches:
      - main 


env:
  NODE_VERSION:  "22"

jobs:
  build-mini-curso-devops:
    runs-on: ubuntu-latest
    steps:
      - name: Download Repo
        uses: actions/checkout@v4

      - name: Prepara S.O para Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION}}
      - name: Ajuste path e Adiciona Files

        run: | 
          pwd && ls -alh 
          cd mini-curso-devops
          cat << EOF >> vite.config.js
          import { defineConfig } from 'vite'
          // https://vitejs.dev/config/
          export default defineConfig({
          // Adicione esta linha:
          base: '/mini-curso-devops/', 
          } )
          EOF
          ls -alh
          
      - name: Instala dependencias e Build
        run: |
          pwd && ls -alh  
          cd mini-curso-devops         
          npm install
          npm run build

      - name: Fazer o Upload do codigo
        uses: actions/upload-artifact@v4
        with: 
          name: dist-files
          path: mini-curso-devops/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build-mini-curso-devops
    steps:
      - name: Download do Arquivos 
        uses: actions/download-artifact@v4
        with: 
          name: dist-files
          path: dist
      - name: Enviar arquivos para Server 
        run: | 
          ls -alh 
          mkdir -p ~/.ssh
          echo "${{ secrets.KOEHLERLABS_KEY_PROD }}" > ~/.ssh/koehlerlabs-key-prod.pem
          chmod 600 ~/.ssh/koehlerlabs-key-prod.pem
          scp -i ~/.ssh/koehlerlabs-key-prod.pem  -o StrictHostKeyChecking=no -r dist/* ubuntu@ec2-54-234-56-50.compute-1.amazonaws.com:/var/www/html/mini-curso-devops
